source 'https://rubygems.org'
gem "rulers", :path => "/Users/rconnolly/RebuildingRails/rulers"

gem 'webrick', '~> 1.3', '>= 1.3.1'

group :development do 
    gem 'rerun'
    gem 'listen', '=1.3.1'
end
